In [14]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf
import cv2
import mediapipe as mp
from keras.models import load_model
import numpy as np
import time
import pandas as pd

model = load_model('C:/Users/khush/OneDrive/Desktop/AIDI/SEM-2/AIDI 1011 - Artificial Intelligence Project/SignLanguageDetectionApp/smnist.h5')

mphands = mp.solutions.hands
hands = mphands.Hands()
mp_drawing = mp.solutions.drawing_utils
cap = cv2.VideoCapture(0)

_, frame = cap.read()

h, w, c = frame.shape
output = []
img_counter = 0
analysisframe = ''
letterpred = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y']
while True:
    _, frame = cap.read()

    k = cv2.waitKey(1)
    if k%256 == 27:
        # ESC pressed
        print("Escape hit, closing...")
        break
    elif k%256 == 32:
        # SPACE pressed
        analysisframe = frame
        showframe = analysisframe
        cv2.imshow("Frame", showframe)
        framergbanalysis = cv2.cvtColor(analysisframe, cv2.COLOR_BGR2RGB)
        resultanalysis = hands.process(framergbanalysis)
        hand_landmarksanalysis = resultanalysis.multi_hand_landmarks
        if hand_landmarksanalysis:
            for handLMsanalysis in hand_landmarksanalysis:
                x_max = 0
                y_max = 0
                x_min = w
                y_min = h
                for lmanalysis in handLMsanalysis.landmark:
                    x, y = int(lmanalysis.x * w), int(lmanalysis.y * h)
                    if x > x_max:
                        x_max = x
                    if x < x_min:
                        x_min = x
                    if y > y_max:
                        y_max = y
                    if y < y_min:
                        y_min = y
                y_min -= 20
                y_max += 20
                x_min -= 20
                x_max += 20 
        elif k%256 == 26:
            output.append(" ")


        analysisframe = cv2.cvtColor(analysisframe, cv2.COLOR_BGR2GRAY)
        analysisframe = analysisframe[y_min:y_max, x_min:x_max]
        analysisframe = cv2.resize(analysisframe,(28,28))


        nlist = []
        rows,cols = analysisframe.shape
        for i in range(rows):
            for j in range(cols):
                k = analysisframe[i,j]
                nlist.append(k)
        
        datan = pd.DataFrame(nlist).T
        colname = []
        for val in range(784):
            colname.append(val)
        datan.columns = colname

        pixeldata = datan.values
        pixeldata = pixeldata / 255
        pixeldata = pixeldata.reshape(-1,28,28,1)
        print(pixeldata)
        prediction = model.predict(pixeldata)
        predarray = np.array(prediction[0])
        letter_prediction_dict = {letterpred[i]: predarray[i] for i in range(len(letterpred))}
        predarrayordered = sorted(predarray, reverse=True)
        high1 = predarrayordered[0]
        high2 = predarrayordered[1]
        high3 = predarrayordered[2]
        for key,value in letter_prediction_dict.items():
            if value==high1:
                print("Predicted Character 1: ", key)
                print('Confidence 1: ', 100*value)
                output.append(key)
            elif value==high2:
                print("Predicted Character 2: ", key)
                print('Confidence 2: ', 100*value)
            elif value==high3:
                print("Predicted Character 3: ", key)
                print('Confidence 3: ', 100*value)
        time.sleep(5)

    framergb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    result = hands.process(framergb)
    hand_landmarks = result.multi_hand_landmarks
    if hand_landmarks:
        for handLMs in hand_landmarks:
            x_max = 0
            y_max = 0
            x_min = w
            y_min = h
            for lm in handLMs.landmark:
                x, y = int(lm.x * w), int(lm.y * h)
                if x > x_max:
                    x_max = x
                if x < x_min:
                    x_min = x
                if y > y_max:
                    y_max = y
                if y < y_min:
                    y_min = y
            y_min -= 20
            y_max += 20 
            x_min -= 20
            x_max += 20
            cv2.rectangle(frame, (x_min, y_min), (x_max, y_max), (0, 255, 0), 2)
    cv2.imshow("Frame", frame)

cap.release()
cv2.destroyAllWindows()
print(output)

[[[[0.09803922]
   [0.12156863]
   [0.12941176]
   [0.12156863]
   [0.12156863]
   [0.36470588]
   [0.4       ]
   [0.65098039]
   [0.63529412]
   [0.30588235]
   [0.42745098]
   [0.45882353]
   [0.48235294]
   [0.49411765]
   [0.50588235]
   [0.51372549]
   [0.52156863]
   [0.52156863]
   [0.52941176]
   [0.51764706]
   [0.52156863]
   [0.51764706]
   [0.50588235]
   [0.49803922]
   [0.50196078]
   [0.49019608]
   [0.49411765]
   [0.49019608]]

  [[0.63921569]
   [0.61176471]
   [0.58823529]
   [0.56862745]
   [0.32156863]
   [0.10980392]
   [0.50980392]
   [0.65490196]
   [0.65098039]
   [0.20784314]
   [0.34509804]
   [0.31764706]
   [0.30196078]
   [0.28235294]
   [0.28235294]
   [0.43137255]
   [0.45490196]
   [0.47843137]
   [0.47843137]
   [0.48627451]
   [0.49411765]
   [0.49803922]
   [0.49019608]
   [0.48627451]
   [0.49411765]
   [0.56470588]
   [0.50980392]
   [0.49019608]]

  [[0.67843137]
   [0.6745098 ]
   [0.65882353]
   [0.64705882]
   [0.63137255]
   [0.22745098]
   [

1/1 [==============================] - 0s 64ms/step
Predicted Character 2:  I
Confidence 2:  0.04129453736823052
Predicted Character 1:  P
Confidence 1:  99.89591836929321
Predicted Character 3:  W
Confidence 3:  0.02699747565202415
[[[[0.73333333]
   [0.73333333]
   [0.72941176]
   [0.70588235]
   [0.6627451 ]
   [0.55294118]
   [0.16078431]
   [0.1254902 ]
   [0.38039216]
   [0.25490196]
   [0.16078431]
   [0.14509804]
   [0.15294118]
   [0.14901961]
   [0.16078431]
   [0.16862745]
   [0.1254902 ]
   [0.1254902 ]
   [0.12156863]
   [0.13333333]
   [0.15294118]
   [0.17647059]
   [0.21568627]
   [0.18823529]
   [0.12941176]
   [0.13333333]
   [0.18039216]
   [0.0745098 ]]

  [[0.74117647]
   [0.7372549 ]
   [0.71764706]
   [0.71372549]
   [0.68235294]
   [0.58039216]
   [0.16862745]
   [0.20784314]
   [0.43529412]
   [0.55686275]
   [0.56862745]
   [0.5254902 ]
   [0.49019608]
   [0.19607843]
   [0.26666667]
   [0.41176471]
   [0.14117647]
   [0.25098039]
   [0.1372549 ]
   [0.1450980

1/1 [==============================] - 0s 27ms/step
Predicted Character 2:  K
Confidence 2:  0.07597465300932527
Predicted Character 1:  P
Confidence 1:  99.837327003479
Predicted Character 3:  U
Confidence 3:  0.0446145364549011
Escape hit, closing...
['P', 'P']


In [10]:
aasthakhushi = ''.join(output)


In [11]:
aasthakhushi

'PP'

In [12]:
!pip install gtts

In [13]:
from gtts import gTTS
import os

# Text to be converted to speech
text = aasthakhushi

# Language in which the speech should be generated
language = "en"

# Create a gTTS object
tts = gTTS(text=text, lang=language, slow=False)

# Save the audio file
tts.save("hello.mp3")

# Play the audio file
os.system("mpg321 hello.mp3")

from gtts import gTTS
from IPython.display import Audio
from IPython.display import display
sound_file = 'hello.mp3'
wn = Audio(sound_file, autoplay=True) ##
display(wn)##

In [8]:
!pip install mediapipe